import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { AlertTriangle, ArrowLeft, RotateCcw, ShieldAlert, Users } from 'lucide-react'
import { analysisApi, jobApi } from '../lib/api'
import { usePrincipal } from '../hooks/usePrincipal'
import { Button, Card, ErrorCard, LoadingCards, PageNav, SectionLabel, SuccessNote } from '../components/ui'

const labels={audio_quality:'Audio quality',diarization:'Speaker diarization',face_detection:'Face detection',visual_clarity:'Visual clarity',overall:'Overall confidence'}

export function ConfidenceReviewPage(){const access=usePrincipal();const qc=useQueryClient();const {analysisId}=useParams();const query=useQuery({queryKey:['analysis',analysisId],queryFn:()=>analysisApi.detail(analysisId)});const retry=useMutation({mutationFn:jobApi.retry,onSuccess:()=>{qc.invalidateQueries({queryKey:['analysis',analysisId]});qc.invalidateQueries({queryKey:['jobs']})}});if(query.isLoading)return <div className="page"><LoadingCards/></div>;if(query.isError)return <div className="page"><ErrorCard error={query.error}/></div>;const analysis=query.data;const confidence=analysis.modality_confidence||{};const unavailable=analysis.recipes.filter(recipe=>recipe.status==='NOT_SCORABLE');return <div className="page confidence-page">
  <PageNav/><div className="page-heading"><div><SectionLabel blue>DEGRADED EVIDENCE REVIEW</SectionLabel><h2>Confidence requires attention</h2><p>Review which modalities weakened this Analysis before relying on its result.</p></div></div>
  <div className="degraded-banner"><ShieldAlert size={24}/><div><strong>{Math.round((confidence.overall??analysis.confidence)*100)}% overall confidence</strong><span>The score is preserved as returned by the Application API; low-confidence inputs are never silently converted to zero.</span></div></div>
  <div className="confidence-grid"><Card><SectionLabel>MODALITY CONFIDENCE</SectionLabel><div className="confidence-bars">{Object.entries(confidence).map(([key,value])=><div key={key} className={key==='overall'?'overall':''}><div><span>{labels[key]||key}</span><strong>{Math.round(value*100)}%</strong></div><div className={value<.6?'low':value<.75?'medium':'good'}><i style={{width:`${value*100}%`}}/></div></div>)}</div></Card><Card><SectionLabel>ANALYSIS IMPACT</SectionLabel><div className="impact-summary"><div><span>Score integrity</span><strong>{analysis.score_integrity}</strong></div><div><span>Publishable</span><strong>{analysis.publishable?'Yes':'No'}</strong></div><div><span>Blocking Recipes</span><strong>{(analysis.blocking_recipes||[]).join(', ')||'None'}</strong></div></div>{unavailable.map(recipe=><div className="blocked-recipe" key={recipe.recipe_id}><AlertTriangle size={15}/><div><strong>{recipe.recipe_id} · {recipe.recipe_name}</strong><span>{recipe.why||recipe.finding_text||'Not enough evidence'}</span>{recipe.failed_job_id&&<small>Failed job {recipe.failed_job_id}</small>}</div></div>)}</Card></div>
  {retry.isSuccess&&<SuccessNote>Retry submitted for job {analysis.failed_job_id}.</SuccessNote>}{retry.isError&&<div className="warning-callout"><p>{retry.error.message}</p></div>}
  <Card className="confidence-actions"><div><strong>Available actions</strong><span>{analysis.failed_job_id?'A failed processing job is linked and can be retried without guessing.':'No failed processing job is associated with this degraded result.'}</span></div><Link className="button secondary" to={`/meetings/${analysis.meeting_id}?tab=Evidence`}>Inspect evidence</Link><Link className="button secondary" to={`/meetings/${analysis.meeting_id}?tab=Participants`}><Users size={14}/>Resolve participants</Link>{analysis.status==='draft'&&<Link className="button warning" to={`/meetings/${analysis.meeting_id}?tab=Intelligence&analysis=${analysis.analysis_id}`}>Proceed with caution</Link>}{analysis.failed_job_id&&access.can('job.control')&&<Button disabled={retry.isPending} onClick={()=>retry.mutate(analysis.failed_job_id)}><RotateCcw size={14}/>Retry processing</Button>}</Card>
  </div>}
