import { useEffect, useState } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, Save, ShieldCheck } from 'lucide-react'
import { analysisApi } from '../lib/api'
import { useUnsavedChanges } from '../hooks/useUnsavedChanges'
import { usePrincipal } from '../hooks/usePrincipal'
import { Button, Card, ErrorCard, LoadingCards, PageNav, SectionLabel, SuccessNote } from '../components/ui'

export function HumanScoringPage(){const access=usePrincipal();const {analysisId}=useParams();const query=useQuery({queryKey:['analysis',analysisId],queryFn:()=>analysisApi.detail(analysisId)});const [scores,setScores]=useState({});const [savedSnapshot,setSavedSnapshot]=useState('{}');useEffect(()=>{if(query.data){const initial=Object.fromEntries(query.data.recipes.filter(recipe=>recipe.kind==='human').map(recipe=>[recipe.recipe_id,recipe.human_slider||1]));setScores(initial);setSavedSnapshot(JSON.stringify(initial))}},[query.data]);const dirty=Boolean(query.data)&&JSON.stringify(scores)!==savedSnapshot;useUnsavedChanges(dirty);const save=useMutation({mutationFn:()=>analysisApi.setHumanScores(analysisId,scores),onSuccess:()=>setSavedSnapshot(JSON.stringify(scores))});if(query.isLoading||access.isLoading)return <div className="page"><LoadingCards/></div>;if(query.isError)return <div className="page"><ErrorCard error={query.error}/></div>;const human=query.data.recipes.filter(recipe=>recipe.kind==='human');const back=`/meetings/${query.data.meeting_id}?tab=Intelligence&analysis=${analysisId}`;const canScore=access.can('analysis.human_score');return <div className="page"><PageNav/><div className="page-heading"><div><SectionLabel blue>HUMAN SCORING</SectionLabel><h2>Subjective parameters</h2><p>Explicit reviewer judgement, separate from AI evidence and notes.</p></div></div>{!canScore&&<div className="permissions-placeholder"><p>Your live permissions allow this Analysis to be viewed but not human-scored.</p></div>}{save.isSuccess&&<SuccessNote>Human scores saved and the Analysis was deterministically recalculated.</SuccessNote>}{save.isError&&<div className="warning-callout"><p>{save.error.message}</p></div>}<Card><div className="human-rules"><ShieldCheck size={17}/><span>Parameters are predefined. Slider range is 1–10. No free-text score justification is accepted on this screen.</span></div><div className="human-score-list">{human.map(recipe=><div className="human-score-row" key={recipe.recipe_id}><div><strong>{recipe.recipe_name}</strong><span>{recipe.recipe_id} · {recipe.weight}% weight · {recipe.polarity==='-'?'Risk inversion':'Positive basis'}</span></div><input aria-label={`${recipe.recipe_name} score`} type="range" min="1" max="10" step="1" disabled={!canScore} value={scores[recipe.recipe_id]||1} onChange={event=>setScores({...scores,[recipe.recipe_id]:Number(event.target.value)})}/><output>{scores[recipe.recipe_id]||1}<small>/10</small></output></div>)}</div>{human.length===0&&<div className="no-results">This Analysis has no enabled human-scored parameters.</div>}<div className="human-actions"><Link className="button secondary" to={back}>Cancel</Link>{canScore&&<Button disabled={!human.length||!dirty||save.isPending} onClick={()=>save.mutate()}><Save size={14}/>Save scores</Button>}</div></Card></div>}
