import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link, useParams } from 'react-router-dom'
import { AlertTriangle, ArrowLeft, Download, FileText } from 'lucide-react'
import { analysisApi, exportApi } from '../lib/api'
import { usePrincipal } from '../hooks/usePrincipal'
import { Button, Card, ErrorCard, LoadingCards, PageNav, SectionLabel, SuccessNote } from '../components/ui'

export function ReportPreviewPage(){const access=usePrincipal();const qc=useQueryClient();const {analysisId}=useParams();const query=useQuery({queryKey:['report-preview',analysisId],queryFn:()=>analysisApi.reportPreview(analysisId)});const history=useQuery({queryKey:['exports',analysisId],queryFn:()=>exportApi.list(analysisId),enabled:access.can('report.read')});const exp=useMutation({mutationFn:format=>analysisApi.exportReport(analysisId,format),onSuccess:()=>qc.invalidateQueries({queryKey:['exports',analysisId]})});if(query.isLoading)return <div className="page"><LoadingCards/></div>;if(query.isError)return <div className="page"><ErrorCard error={query.error}/></div>;const report=query.data;const canExport=access.can('report.export');return <div className="page report-preview-page"><PageNav/>
  <div className="page-heading"><div><SectionLabel blue>REPORT PREVIEW</SectionLabel><h2>{report.title}</h2><p>Server-rendered content · generated {new Date(report.generated_at).toLocaleString()}</p></div>{canExport&&<div className="heading-actions">{['pdf','html','json'].map(format=><Button key={format} variant={format==='pdf'?'primary':'secondary'} disabled={!report.publishable||exp.isPending} onClick={()=>exp.mutate(format)}><Download size={14}/>{format.toUpperCase()}</Button>)}</div>}</div>
  {!report.publishable&&<div className="degraded-banner"><AlertTriangle/><div><strong>Export blocked</strong><span>{report.blocking_reason}</span></div></div>}{!canExport&&<div className="permissions-placeholder"><p>Your live permissions allow report viewing but not export.</p></div>}{exp.isSuccess&&<SuccessNote>Export ready: <a href={exp.data.download_url}>Download {exp.data.format.toUpperCase()}</a></SuccessNote>}{exp.isError&&<div className="warning-callout"><p>{exp.error.message}</p></div>}
  <nav className="report-section-nav" aria-label="Report sections">{report.sections.map(section=><a href={`#report-${section.key}`} key={section.key}><FileText size={14}/><span>{section.title}</span><strong>{section.rows.length}</strong></a>)}</nav><Card className="report-cover"><FileText size={28}/><div><strong>{report.meta.meeting_label}</strong><span>{report.meta.source_filename} · {report.meta.recorded_on} · {report.meta.room_name}</span></div><div className="report-score"><strong>{report.meta.overall_score??'—'}</strong><span>{report.meta.overall_band} · {report.meta.evidence_coverage}% evidence</span></div></Card>
  {report.sections.map(section=><Card id={`report-${section.key}`} className="report-section" key={section.key}><SectionLabel>{section.title}</SectionLabel>{section.note&&<p className="report-note">{section.note}</p>}<div className="report-rows">{section.rows.map((row,index)=><dl key={index}>{Object.entries(row).map(([key,value])=><div key={key}><dt>{key.replaceAll('_',' ')}</dt><dd>{value==null?'—':String(value)}</dd></div>)}</dl>)}</div>{section.rows.length===0&&<div className="no-results">No items in this section.</div>}</Card>)}
  <Card className="report-section"><SectionLabel>EXPORT HISTORY</SectionLabel>{history.isLoading?<LoadingCards/>:history.isError?<ErrorCard error={history.error}/>:<div className="export-history">{history.data.map(record=><a href={record.download_url} key={record.export_id}><FileText size={15}/><div><strong>{record.format.toUpperCase()}</strong><span>{new Date(record.created_at).toLocaleString()} · {record.created_by} · {(record.bytes/1024).toFixed(1)} KB</span></div><Download size={14}/></a>)}{history.data.length===0&&<div className="no-results">No exports have been generated for this Analysis.</div>}</div>}</Card>
  </div>}
