import { createRequire } from 'module'
const require = createRequire(import.meta.url)
const { chromium } = require('C:/SSGC/POS-ScreenDescription/frontend/node_modules/playwright')
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
const errors = []
page.on('pageerror', (e) => errors.push(e.message))
page.on('console', (msg) => { if (msg.type() === 'error') errors.push(msg.text()) })
await page.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
await page.waitForTimeout(1500)
const url = page.url()
const nav = await page.locator('nav[aria-label="Primary navigation"]').innerText()
const hasVideo = await page.locator('video.rdi-video').count()
const playing = hasVideo ? await page.locator('video.rdi-video').first().evaluate((el) => ({ paused: el.paused, w: el.videoWidth, ready: el.readyState, src: el.currentSrc })) : null
const body = await page.locator('body').innerText()
console.log('url', url)
console.log('nav', nav.replace(/\s+/g, ' '))
console.log('has meeting home', /Video Library|Meetings|Gallery/.test(nav))
console.log('video', playing)
console.log('ember', body.includes('The Ember Room'))
console.log('errors', errors)
await page.screenshot({ path: 'C:/SSGC/Triton-2/scripts/overview.png' })
await browser.close()
if (errors.length || !hasVideo || !playing?.w) process.exit(1)
