import { createRequire } from 'module'
const require = createRequire(import.meta.url)
const { chromium } = require('C:/SSGC/POS-ScreenDescription/frontend/node_modules/playwright')
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
await page.goto('http://localhost:5173/restaurant', { waitUntil: 'networkidle' })
const dinner = await page.locator('.rdi-kpi').nth(3).innerText()
await page.getByRole('button', { name: 'Lunch', exact: true }).click()
await page.waitForTimeout(300)
const lunch = await page.locator('.rdi-kpi').nth(3).innerText()
await page.getByRole('button', { name: 'Morning', exact: true }).click()
await page.waitForTimeout(300)
const morning = await page.locator('.rdi-kpis').innerText()
console.log('dinner visits', dinner.replace(/\s+/g,' '))
console.log('lunch visits', lunch.replace(/\s+/g,' '))
console.log('morning snippet', morning.replace(/\s+/g,' ').slice(0, 250))
await browser.close()
